service:
  name: chasquis

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-mocha-plugin

provider:
  name: aws
  runtime: nodejs8.10
  environment:
      DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}


functions:
  messengers_create:
    handler: apis.messengers_create
    events:
      - http:
          method: post
          path: messengers
  messengers_get:
    handler: apis.messengers_of
    events:
      - http:
          method: get
          path: messengers/{id}
          request:
            parameters:
              paths:
                id: true
  messengers_update:
      handler: apis.messengers_of
      events:
        - http:
            method: patch
            path: messengers/{id}
            request:
              parameters:
                paths:
                  id: true
