service:
  name: chasquis

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: develop
  environment:
      DYNAMODB_TABLE_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_PREFIX}_MESSENGERS"

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  messengers_create:
    handler: apis.messengers_create
    events:
      - http:
          method: post
          cors: true
          path: messengers
  messengers_get:
    handler: apis.messengers_of
    events:
      - http:
          method: get
          path: messengers/{id}
          cors: true
          request:
            parameters:
              paths:
                id: true
  messengers_update:
      handler: apis.messengers_update
      events:
        - http:
            method: patch
            path: messengers/{id}
            cors: true
            request:
              parameters:
                paths:
                  id: true
  messengers_delete:
      handler: apis.messengers_delete
      events:
        - http:
            method: delete
            path: messengers/{id}
            cors: true
            request:
              parameters:
                paths:
                  id: true
resources:
  Resources:
    Messengers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage, self:provider.stage}_MESSENGERS
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1